/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VoiceExpenseRouteImport } from './routes/voice-expense'
import { Route as SplitRouteImport } from './routes/split'
import { Route as SmsPermissionRouteImport } from './routes/sms-permission'
import { Route as ShareReportRouteImport } from './routes/share-report'
import { Route as ReceiptScanRouteImport } from './routes/receipt-scan'
import { Route as QuickCashRouteImport } from './routes/quick-cash'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IncomeSetupRouteImport } from './routes/income-setup'
import { Route as GoalsSetupRouteImport } from './routes/goals-setup'
import { Route as GoalCreateRouteImport } from './routes/goal-create'
import { Route as GoalCompleteRouteImport } from './routes/goal-complete'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AiLoadingRouteImport } from './routes/ai-loading'
import { Route as AddMenuRouteImport } from './routes/add-menu'
import { Route as AddExpenseRouteImport } from './routes/add-expense'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizAchievementsRouteImport } from './routes/quiz.achievements'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppQuizRouteImport } from './routes/_app.quiz'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHubRouteImport } from './routes/_app.hub'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppGoalSavingRouteImport } from './routes/_app.goal-saving'
import { Route as AppGoalDetailsRouteImport } from './routes/_app.goal-details'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as QuizCategoryIdRouteImport } from './routes/quiz.category.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceExpenseRoute = VoiceExpenseRouteImport.update({
  id: '/voice-expense',
  path: '/voice-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsPermissionRoute = SmsPermissionRouteImport.update({
  id: '/sms-permission',
  path: '/sms-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareReportRoute = ShareReportRouteImport.update({
  id: '/share-report',
  path: '/share-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptScanRoute = ReceiptScanRouteImport.update({
  id: '/receipt-scan',
  path: '/receipt-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickCashRoute = QuickCashRouteImport.update({
  id: '/quick-cash',
  path: '/quick-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeSetupRoute = IncomeSetupRouteImport.update({
  id: '/income-setup',
  path: '/income-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsSetupRoute = GoalsSetupRouteImport.update({
  id: '/goals-setup',
  path: '/goals-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalCreateRoute = GoalCreateRouteImport.update({
  id: '/goal-create',
  path: '/goal-create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalCompleteRoute = GoalCompleteRouteImport.update({
  id: '/goal-complete',
  path: '/goal-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLoadingRoute = AiLoadingRouteImport.update({
  id: '/ai-loading',
  path: '/ai-loading',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMenuRoute = AddMenuRouteImport.update({
  id: '/add-menu',
  path: '/add-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AddExpenseRoute = AddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAchievementsRoute = QuizAchievementsRouteImport.update({
  id: '/quiz/achievements',
  path: '/quiz/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHubRoute = AppHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalSavingRoute = AppGoalSavingRouteImport.update({
  id: '/goal-saving',
  path: '/goal-saving',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalDetailsRoute = AppGoalDetailsRouteImport.update({
  id: '/goal-details',
  path: '/goal-details',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const QuizCategoryIdRoute = QuizCategoryIdRouteImport.update({
  id: '/quiz/category/$id',
  path: '/quiz/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-expense': typeof AddExpenseRoute
  '/add-menu': typeof AddMenuRoute
  '/ai-loading': typeof AiLoadingRoute
  '/explore': typeof ExploreRoute
  '/goal-complete': typeof GoalCompleteRoute
  '/goal-create': typeof GoalCreateRoute
  '/goals-setup': typeof GoalsSetupRoute
  '/income-setup': typeof IncomeSetupRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/premium': typeof PremiumRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-cash': typeof QuickCashRoute
  '/receipt-scan': typeof ReceiptScanRoute
  '/share-report': typeof ShareReportRoute
  '/sms-permission': typeof SmsPermissionRoute
  '/split': typeof SplitRoute
  '/voice-expense': typeof VoiceExpenseRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AppAchievementsRoute
  '/budget': typeof AppBudgetRoute
  '/coach': typeof AppCoachRoute
  '/expenses': typeof AppExpensesRoute
  '/forecast': typeof AppForecastRoute
  '/goal-details': typeof AppGoalDetailsRoute
  '/goal-saving': typeof AppGoalSavingRoute
  '/goals': typeof AppGoalsRoute
  '/home': typeof AppHomeRoute
  '/hub': typeof AppHubRoute
  '/profile': typeof AppProfileRoute
  '/quiz': typeof AppQuizRoute
  '/report': typeof AppReportRoute
  '/quiz/achievements': typeof QuizAchievementsRoute
  '/quiz/category/$id': typeof QuizCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-expense': typeof AddExpenseRoute
  '/add-menu': typeof AddMenuRoute
  '/ai-loading': typeof AiLoadingRoute
  '/explore': typeof ExploreRoute
  '/goal-complete': typeof GoalCompleteRoute
  '/goal-create': typeof GoalCreateRoute
  '/goals-setup': typeof GoalsSetupRoute
  '/income-setup': typeof IncomeSetupRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/premium': typeof PremiumRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-cash': typeof QuickCashRoute
  '/receipt-scan': typeof ReceiptScanRoute
  '/share-report': typeof ShareReportRoute
  '/sms-permission': typeof SmsPermissionRoute
  '/split': typeof SplitRoute
  '/voice-expense': typeof VoiceExpenseRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AppAchievementsRoute
  '/budget': typeof AppBudgetRoute
  '/coach': typeof AppCoachRoute
  '/expenses': typeof AppExpensesRoute
  '/forecast': typeof AppForecastRoute
  '/goal-details': typeof AppGoalDetailsRoute
  '/goal-saving': typeof AppGoalSavingRoute
  '/goals': typeof AppGoalsRoute
  '/home': typeof AppHomeRoute
  '/hub': typeof AppHubRoute
  '/profile': typeof AppProfileRoute
  '/quiz': typeof AppQuizRoute
  '/report': typeof AppReportRoute
  '/quiz/achievements': typeof QuizAchievementsRoute
  '/quiz/category/$id': typeof QuizCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/add-expense': typeof AddExpenseRoute
  '/add-menu': typeof AddMenuRoute
  '/ai-loading': typeof AiLoadingRoute
  '/explore': typeof ExploreRoute
  '/goal-complete': typeof GoalCompleteRoute
  '/goal-create': typeof GoalCreateRoute
  '/goals-setup': typeof GoalsSetupRoute
  '/income-setup': typeof IncomeSetupRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/premium': typeof PremiumRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/quick-cash': typeof QuickCashRoute
  '/receipt-scan': typeof ReceiptScanRoute
  '/share-report': typeof ShareReportRoute
  '/sms-permission': typeof SmsPermissionRoute
  '/split': typeof SplitRoute
  '/voice-expense': typeof VoiceExpenseRoute
  '/welcome': typeof WelcomeRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/goal-details': typeof AppGoalDetailsRoute
  '/_app/goal-saving': typeof AppGoalSavingRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/hub': typeof AppHubRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quiz': typeof AppQuizRoute
  '/_app/report': typeof AppReportRoute
  '/quiz/achievements': typeof QuizAchievementsRoute
  '/quiz/category/$id': typeof QuizCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-expense'
    | '/add-menu'
    | '/ai-loading'
    | '/explore'
    | '/goal-complete'
    | '/goal-create'
    | '/goals-setup'
    | '/income-setup'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/premium'
    | '/profile-setup'
    | '/quick-cash'
    | '/receipt-scan'
    | '/share-report'
    | '/sms-permission'
    | '/split'
    | '/voice-expense'
    | '/welcome'
    | '/achievements'
    | '/budget'
    | '/coach'
    | '/expenses'
    | '/forecast'
    | '/goal-details'
    | '/goal-saving'
    | '/goals'
    | '/home'
    | '/hub'
    | '/profile'
    | '/quiz'
    | '/report'
    | '/quiz/achievements'
    | '/quiz/category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-expense'
    | '/add-menu'
    | '/ai-loading'
    | '/explore'
    | '/goal-complete'
    | '/goal-create'
    | '/goals-setup'
    | '/income-setup'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/premium'
    | '/profile-setup'
    | '/quick-cash'
    | '/receipt-scan'
    | '/share-report'
    | '/sms-permission'
    | '/split'
    | '/voice-expense'
    | '/welcome'
    | '/achievements'
    | '/budget'
    | '/coach'
    | '/expenses'
    | '/forecast'
    | '/goal-details'
    | '/goal-saving'
    | '/goals'
    | '/home'
    | '/hub'
    | '/profile'
    | '/quiz'
    | '/report'
    | '/quiz/achievements'
    | '/quiz/category/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/add-expense'
    | '/add-menu'
    | '/ai-loading'
    | '/explore'
    | '/goal-complete'
    | '/goal-create'
    | '/goals-setup'
    | '/income-setup'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/premium'
    | '/profile-setup'
    | '/quick-cash'
    | '/receipt-scan'
    | '/share-report'
    | '/sms-permission'
    | '/split'
    | '/voice-expense'
    | '/welcome'
    | '/_app/achievements'
    | '/_app/budget'
    | '/_app/coach'
    | '/_app/expenses'
    | '/_app/forecast'
    | '/_app/goal-details'
    | '/_app/goal-saving'
    | '/_app/goals'
    | '/_app/home'
    | '/_app/hub'
    | '/_app/profile'
    | '/_app/quiz'
    | '/_app/report'
    | '/quiz/achievements'
    | '/quiz/category/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AddExpenseRoute: typeof AddExpenseRoute
  AddMenuRoute: typeof AddMenuRoute
  AiLoadingRoute: typeof AiLoadingRoute
  ExploreRoute: typeof ExploreRoute
  GoalCompleteRoute: typeof GoalCompleteRoute
  GoalCreateRoute: typeof GoalCreateRoute
  GoalsSetupRoute: typeof GoalsSetupRoute
  IncomeSetupRoute: typeof IncomeSetupRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  PremiumRoute: typeof PremiumRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  QuickCashRoute: typeof QuickCashRoute
  ReceiptScanRoute: typeof ReceiptScanRoute
  ShareReportRoute: typeof ShareReportRoute
  SmsPermissionRoute: typeof SmsPermissionRoute
  SplitRoute: typeof SplitRoute
  VoiceExpenseRoute: typeof VoiceExpenseRoute
  WelcomeRoute: typeof WelcomeRoute
  QuizAchievementsRoute: typeof QuizAchievementsRoute
  QuizCategoryIdRoute: typeof QuizCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-expense': {
      id: '/voice-expense'
      path: '/voice-expense'
      fullPath: '/voice-expense'
      preLoaderRoute: typeof VoiceExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-permission': {
      id: '/sms-permission'
      path: '/sms-permission'
      fullPath: '/sms-permission'
      preLoaderRoute: typeof SmsPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-report': {
      id: '/share-report'
      path: '/share-report'
      fullPath: '/share-report'
      preLoaderRoute: typeof ShareReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-scan': {
      id: '/receipt-scan'
      path: '/receipt-scan'
      fullPath: '/receipt-scan'
      preLoaderRoute: typeof ReceiptScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-cash': {
      id: '/quick-cash'
      path: '/quick-cash'
      fullPath: '/quick-cash'
      preLoaderRoute: typeof QuickCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-setup': {
      id: '/income-setup'
      path: '/income-setup'
      fullPath: '/income-setup'
      preLoaderRoute: typeof IncomeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals-setup': {
      id: '/goals-setup'
      path: '/goals-setup'
      fullPath: '/goals-setup'
      preLoaderRoute: typeof GoalsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal-create': {
      id: '/goal-create'
      path: '/goal-create'
      fullPath: '/goal-create'
      preLoaderRoute: typeof GoalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal-complete': {
      id: '/goal-complete'
      path: '/goal-complete'
      fullPath: '/goal-complete'
      preLoaderRoute: typeof GoalCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-loading': {
      id: '/ai-loading'
      path: '/ai-loading'
      fullPath: '/ai-loading'
      preLoaderRoute: typeof AiLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-menu': {
      id: '/add-menu'
      path: '/add-menu'
      fullPath: '/add-menu'
      preLoaderRoute: typeof AddMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-expense': {
      id: '/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AddExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/achievements': {
      id: '/quiz/achievements'
      path: '/quiz/achievements'
      fullPath: '/quiz/achievements'
      preLoaderRoute: typeof QuizAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hub': {
      id: '/_app/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AppHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goal-saving': {
      id: '/_app/goal-saving'
      path: '/goal-saving'
      fullPath: '/goal-saving'
      preLoaderRoute: typeof AppGoalSavingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goal-details': {
      id: '/_app/goal-details'
      path: '/goal-details'
      fullPath: '/goal-details'
      preLoaderRoute: typeof AppGoalDetailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/quiz/category/$id': {
      id: '/quiz/category/$id'
      path: '/quiz/category/$id'
      fullPath: '/quiz/category/$id'
      preLoaderRoute: typeof QuizCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppCoachRoute: typeof AppCoachRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGoalDetailsRoute: typeof AppGoalDetailsRoute
  AppGoalSavingRoute: typeof AppGoalSavingRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppHubRoute: typeof AppHubRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuizRoute: typeof AppQuizRoute
  AppReportRoute: typeof AppReportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppCoachRoute: AppCoachRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppForecastRoute: AppForecastRoute,
  AppGoalDetailsRoute: AppGoalDetailsRoute,
  AppGoalSavingRoute: AppGoalSavingRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHomeRoute: AppHomeRoute,
  AppHubRoute: AppHubRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuizRoute: AppQuizRoute,
  AppReportRoute: AppReportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AddExpenseRoute: AddExpenseRoute,
  AddMenuRoute: AddMenuRoute,
  AiLoadingRoute: AiLoadingRoute,
  ExploreRoute: ExploreRoute,
  GoalCompleteRoute: GoalCompleteRoute,
  GoalCreateRoute: GoalCreateRoute,
  GoalsSetupRoute: GoalsSetupRoute,
  IncomeSetupRoute: IncomeSetupRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  PremiumRoute: PremiumRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  QuickCashRoute: QuickCashRoute,
  ReceiptScanRoute: ReceiptScanRoute,
  ShareReportRoute: ShareReportRoute,
  SmsPermissionRoute: SmsPermissionRoute,
  SplitRoute: SplitRoute,
  VoiceExpenseRoute: VoiceExpenseRoute,
  WelcomeRoute: WelcomeRoute,
  QuizAchievementsRoute: QuizAchievementsRoute,
  QuizCategoryIdRoute: QuizCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
